### ISSUE TITLE
writerHTMLMathMethod not getting applied whatsoever

### ISSUE THREAD

**Issue by mactonya** [jaspervdj/hakyll#1006]
Trying to use hakyll to do math blog, but for whatever reason when I am trying to convert the maths, the config `{ writerHTMLMathMethod = KaTeX "" }` just refuses to work, so it turns something simple like `a^2+b^2=c^2` to `<em>a</em><sup>2</sup> + <em>b</em><sup>2</sup> = <em>c</em><sup>2</sup></span>`
```
    match "posts/*" $ do
        let writerOptions = defaultHakyllWriterOptions
                            { writerHTMLMathMethod = KaTeX "" }
        route $ setExtension "html"
        compile $ pandocCompilerWith defaultHakyllReaderOptions writerOptions
            >>= loadAndApplyTemplate "templates/post.html"    postCtx
            >>= loadAndApplyTemplate "templates/default.html" postCtx
            >>= relativizeUrls
```
local pandoc can apply the flags normally; any possible idea on why this could happen?

**Comment by chungyc** [comment]
It didn't work for me either.  With some random fiddling, though, I managed to use KaTeX by using the MathJax as the `writerHTMLMathMethod` and including the necessary Javascript.

For an example with my own Hakyll site:

* https://github.com/chungyc/site-personal/blob/d21614fad2610481e859f0de66773e865aea085b/src/Web/Site/Compilers.hs#L104
* https://github.com/chungyc/site-personal/blob/d21614fad2610481e859f0de66773e865aea085b/site/templates/default.html#L37

**Comment by mactonya** [comment]
Seems like `MathJax` is the way to go.

**Comment by Minoru** [comment]
I didn't test this, but I think one needs to pass a URL for KaTeX, or use a default one from `Text.Pandoc.Options`:

```haskell
defaultHakyllWriterOptions { writerHTMLMathMethod = KaTeX defaultKaTeXURL }
```

Apparently that's what `pandoc --katex` does, too:

```
       --katex[=URL]
              Use KaTeX to display embedded TeX math in HTML output.  The URL is the base URL for the KaTeX library.  That directory should contain a katex.min.js and a katex.min.css file.  If a URL  is  not provided, a link to the KaTeX CDN will be inserted.

**Comment by sgraf812** [comment]
As I found out in https://github.com/jgm/pandoc/issues/10209, the reason this does not work is that in order to load KaTeX, one would also need to splice in the value of the pandoc (!) `$math$` variable. (This is *not* the same as the hakyll variable.)

Unfortunately, it is impossible to use the Pandoc API to get a hold of the `Context` which holds the variable. The only way to access its value would be to 

1. define a new template which uses it, 
2. put this template into the `writerTemplate` field of `WriterOptions`
3. Somehow extract the value of `$math$` from the rendered string.

This is pretty awkward. A simple workaround is to splice in the stuff that `$math$` contains by hand. Which would be

```
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script>
```

in `<head>` and

```
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var mathElements = document.getElementsByClassName("math");
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        katex.render(texText.data, mathElements[i], { displayMode: mathElements[i].classList.contains("display"), throwOnError: true } );
      }
    }
  });
</script>
```

at the end of the body.

If I do that and define and use a replacement for `pandocCompiler` as in the OP

```hs
myPandocCompiler = pandocCompilerWith defaultHakyllReaderOptions defaultHakyllWriterOptions
  { writerHTMLMathMethod = MathJax defaultKaTeXURL }
```

Then everything works as exepcted!
