### ISSUE TITLE
No apparent way to add metadata to created item

### ISSUE THREAD

**Issue by robinp** [jaspervdj/hakyll#209]
Item can be created with `makeItem`, but I can't see how one could add metadata to that item.

**Comment by bergus** [comment]
I'd like to reopen this, I've just ran across this as well.

When I `create` items, I want to create metadata for them as well.
Sure, I can work around this by putting `constField` contexts everywhere, but it would be *much* more convenient if I could just use the same contexts for created and matched pages. For example, I'd like to factor out the `>>= loadAndApplyTemplate "templates/default.html" (… <> contexts <> …)` in a global function, but cannot if they require metadata.

I'm not sure whether this metadata should go in `makeItem`, especially since `makeItem` seems to use the underlying identifier which could be who knows what (and mutating its metadata is bad), but there definitely should be a way to attach metadata to the identifiers that are `create`d in the `Rules`.

**Comment by jaspervdj** [comment]
So what I think would be possible is allow someone to pass in `Metadata` when calling `create` in the top-level rules. That way it can be stored sanely in some sort of cache. Then, if `makeItem` uses such an `Identifier`, it returns that `Metadata`.

For "temporary" items created by `makeItem`, the problem is much harder though.

**Comment by bergus** [comment]
Yeah, right, especially as "temporary" items should also have their own identifier (instead of the underlying one).

Btw, for now I worked around my problem by simply putting the metadata in an actual file whose body is then ignored. This actually was the superior solution, at least in my case, as I don't need to edit the `site.hs` to change metadata.

**Comment by krsch** [comment]
There is an alternative way to make dynamic metadata in Hakyll. You can create a `Map` and store it in a snapshot. Then you can have a `Context` that loads this snapshot and does a `lookup` for a key. I made a simple example of this approach in a gist: https://gist.github.com/krsch/42db09721871276c53b8

**Comment by jaspervdj** [comment]
Right, that also works nicely @krsch but it's a bit annoying that you need to have a separate function for looking up the `Metadata`.

**Comment by bergus** [comment]
@krsch: Are those snapshots even cached automatically? That sounds perfect.
