### ISSUE TITLE
Impossible to use copyFileCompiler in same directory than the posts

### ISSUE THREAD

**Issue by cdupont** [jaspervdj/hakyll#338]
I have a copyFileCompiler that should copy some files which are located at the same level than my posts .md files:

    match ("blog/posts/Math/*.txt") $ do
      route   idRoute
      compile copyFileCompiler

However it fails with:

    [ERROR] Hakyll.Core.Compiler.Require.load: blog/posts/Math/t.txt (snapshot _final) was found in the cache, but does not have the right type: expected [Char] but got CopyFile

I noticed this happens only for copying files from the same directory from the posts.

**Comment by jaspervdj** [comment]
It seems that in another place in the file, you are loading the posts using something like:

```haskell
_ <- loadAll "blog/posts/*"
```

This doesn't work, since the `txt` files will also match this pattern, and then cannot be loaded as a string (since they were compiled as `CopyFile`).

You would have to use something like:

```haskell
_ <- loadAll ("blog/posts/*" .&&. complement "blog/posts/Math/*.txt")
```

Does that fix the issue?

**Comment by cdupont** [comment]
Yes, thanks! Sorry for the bug.  
It seems that it was a conflict between two compiler selecting the same files?
Maybe a better error message would be nice? It was hard to understand.

**Comment by ccressent** [comment]
@jaspervdj 
Should this issue be closed?

**Comment by jaspervdj** [comment]
Yes, thanks @ccressent.
