### ISSUE TITLE
Is there a reason that a context is not a functor?

### ISSUE THREAD

**Issue by NorfairKing** [jaspervdj/hakyll#341]
I think the title says it all

**Comment by jaspervdj** [comment]
It simply is not a functor. Note that a simplified version of context would be more or less:
```haskell
newtype Context a = Context (a -> String)
```

If you try implementing the `Functor` instance for that, you will notice that the arrows for the functions are "reversed". That is because while it is not a functor, it is a [contravariant functor](https://hackage.haskell.org/package/contravariant). It doesn't have an instance, though, because `contramap` is rarely used.

**Comment by NorfairKing** [comment]
This is why I asked:
    
    mapContext :: (String -> String) -> Context a -> Context a

**Comment by jaspervdj** [comment]
Yes, so you can see it is "sort of a thing you can map over", but only for `String` though, not for the `a` in the type.

**Comment by NorfairKing** [comment]
Aha, that's what I was missing. Thank you very much!
