### ISSUE TITLE
GitHub Pagest tutorial

### ISSUE THREAD

**Issue by achernyak** [jaspervdj/hakyll#397]
It would be really great to see a tutorial for deploying to GitHub Pages as part of the tutorial section.

GitHub Pages has become a pretty common deployment platform, and an up to date tutorial would be very valuable.

**Comment by narrative** [comment]
I feel as though [this](http://pages.github.com) is fairly straightforward. Would you mind elaborating on what information you're looking for specifically?

**Comment by rainbyte** [comment]
I think it would be interesting to know the recommended workflow:
- Minimal configuration needed.
- How to keep in sync blog src repo with github pages repo.
- A list of common mistakes to avoid (eg. how to prevent _site overwrite when doing rebuild).

For my personal blog I had to do some tweaks:
- Add github pages repo as git submodule.
- Configure sync _site via Makefile and scripts.

**Comment by narrative** [comment]
I've written up [a short guide](https://github.com/narrative/narrative.github.io/blob/develop/GHPAGES.md) for using Hakyll with Github Pages. Let me know if you run into any issues.

**Comment by rainbyte** [comment]
@narrative, Maybe I didn't understand well the idea:
- Are you using a single repo for the src **and** the site?
- Why there are so many branches? (master, publish, develop, ...).
- Is it posible to use `_site` for the blog itself?

My blog src is [here](https://github.com/rainbyte/blog) and I've added [this makefile](https://github.com/rainbyte/blog/blob/master/Makefile) for automatization.
I've a separate repo for the site, as a submodule inside `_site`.

**Comment by narrative** [comment]
Hi. Yes, my guide uses a single GitHub repository for the source and site.

There are 3 branches, but one of them is only temporary.

- ```master``` is the compiled site that you see when you go to ```http://repo.github.io```
- ```develop``` is the Haskell source code.
- ```publish``` is a local version of master that gets deleted following deployment. You may have seen one on my repo that I was testing with and forgot to delete.

So there are only 2 branches, which is the minimum required if you want to keep source separate from build on a single repository.

I'm not sure I understand your third question, since ```_site``` *is* being used for the blog.

Git submodules are not something I have any experience with, but yes there are several possible workflows that all achieve roughly the same result. The method I used is very simple/straightforward.

**Comment by rainbyte** [comment]
About the 3rd question, I mean using `_site` without having to make a copy of it.

The problem appears when you do `site rebuild` and then cp.
Removed and renamed things continue to be there.
Then you have to clean the repo manually.

About branches... Why is `publish` needed?

**Comment by narrative** [comment]
I briefly mention in the guide:

> ...Note that if a file is no longer being produced (for example if you deleted a blog posting), it will continue to persist in your published site until it's been removed from that repository as well.

Is this the problem you're talking about? I don't know a clean solution, and it's not something that comes up often in my use case. But yes, it is a disadvantage to the approach presented in the guide.

```publish``` is simply an alias I give to the ```master``` branch. You can change every occurrence of ```publish``` to ```master``` and it will function identically. Sorry for the confusion.

**Comment by rainbyte** [comment]
Yes, I'm talking about that situation, because I usually remove/rename things.
The `site rebuild` part needs some integration/automatization.

Also, maybe an official guide would need to mention single and multi repo config.
Multi repo is useful if you deploy to various places or migrate from github later.

I'm trying to find if we can make the article simpler/shorter :)
Did you see my makefile? Maybe something could be reused from there.

@narrative thanks for the efforts to solve the issue.

**Comment by jaspervdj** [comment]
After playing around with pages a bit, it seems like it isn't possible to use `_site` as "source directory" in Jenkins. I think publishing from a separate branch is even the recommended solution from Github: <https://help.github.com/articles/using-a-static-site-generator-other-than-jekyll/>.

1. Maybe you can use something like `rsync --delete-excluded` to remove removed files? That fixes the problem @rainbyte raised with deleted/renamed files staying in the repository. I think the exact rsync command you want would be something like:

        rsync -a --filter='P _site/' --delete-excluded _site/ .

    We need to have the filter to **P**rotect `_site/` from getting deleted.

2. Let's rename `publish` to `master`, to prevent confusion. I think most people are used to branches having the same name remotely and locally.

3. I'd like to have the script you linked to in the gist inlined in the tutorial, that way it will be easier to maintain in the future.

4. You should set the metadata so you are correctly indicated as author for the tutorial, as seen in the first lines of this file: <https://raw.githubusercontent.com/jaspervdj/hakyll/master/web/tutorials/using-teasers-in-hakyll.markdown>

**Comment by narrative** [comment]
I appreciate the feedback. Those are definitely some great points, and I learned something new about `rsync` :smiley:.

I've implemented your suggestions in [my latest commit](https://github.com/jaspervdj/hakyll/pull/405/commits/c0e576a8bd51c425ada0dd3801e93af9d70bf0fd).

**Comment by jaspervdj** [comment]
Thanks, I appreciate it!
