### ISSUE TITLE
How to have a list field from metadata

### ISSUE THREAD

**Issue by mrkkrp** [jaspervdj/hakyll#427]
Hi, I need to have a list in context that I could interate with `for` in template. Metadata looks like this:

```
---
libraries: foo bar baz
---
```

I would like to run something like `words` on it and then turn it into `listField`, but I'm having hard time doing that. Any hint how to approach it?

**Comment by jaspervdj** [comment]
You need to first add a `$libraries$` field to your context.  Note that when doing that, you also need specify a context for the items in this list.  We call that `libraryContext`.

```haskell
listFieldWith "libraries" libraryContext (\item -> do
    libraries <- getMetadataField' (itemIdentifier item) "libraries"
    mapM makeItem (words libraries)
```

The `libraryContext` is what you get access to inside your `$for$`.  It can simply be this if you are just using the name:

```haskell
libraryContext = field "name" (\item -> return $ itemBody item)
```

That works because we used `makeItem` to put the library name in the body, and then we are using `itemBody` to get it out again.  This allows us to have a template like:

```html
<ul>
  $for(libraries)$
    <li>$name$</li>
  $endfor$
</ul>
```

**Comment by mrkkrp** [comment]
Thanks!
