### ISSUE TITLE
Cannot render Tags in $tags$

### ISSUE THREAD

**Issue by Rizary** [jaspervdj/hakyll#509]
okay, i have question. I am trying to create tags in my blog, but it does not appear when i do stack myfile-exe build (well i rebuild every time i compile the source). So, here is my snippet..

in my main (doHakyll):
```
doHakyll = hakyll $ do
    tags <- buildTags "posts/*/*/*/*" (fromCapture "blog/tags/*.html")
    pctx <- postCtx tags

    match "posts/*/*/*/*.markdown" $ do
        route $ postsRoute `composeRoutes` setExtension "html"
        compile $ postCompiler pctx
where
      postsRoute = gsubRoute "posts/" (const "blog/posts/")
```

then for postCtx and postCompiler:
```
postCtx :: MonadMetadata m => Tags -> m (Context String)
postCtx tags =
  return $
      tagsField "tags" tags `mappend`
      dateField "date" "%B %e, %Y" `mappend`
      defaultContext


postCompiler :: Context String -> Compiler (Item String)
postCompiler ctx =
    pandocCompiler
      >>= saveSnapshot "content"
      >>= loadAndApplyTemplate "templates/blog.html" ctx
      >>= loadAndApplyTemplate "templates/default.html" ctx
      >>= relativizeUrls
```

In template i add the $tags$ :
```
  <div class="info">

    Tags: $tags$ <br/>
    Created: $date$
  </div>
```

and finally in the post I also add:
```
---
title: Testing
tags: bar1, foo, haskell
date: 30 January 2015
---
```

When I do hakyll build, i got the following output:

```
<div class="info">

    Tags:  <br />
    Created: 30 January 2015
  </div>
```

The tags field was not shown in my post html.

**Comment by jaspervdj** [comment]
Is this available as a repo or a zip somewhere?  That would make it drastically easier for me to reproduce and diagnose the problem.

**Comment by Rizary** [comment]
Hi, i have attached the zip...

the repo does not contain the source code.
[blog.zip](https://github.com/jaspervdj/hakyll/files/692549/blog.zip)

**Comment by jaspervdj** [comment]
Thanks, I checked out the zip file.  I noticed that the `$tags$` are missing _for item_ `blog/tags/bar1.html` -- not of the actual posts.  It is pretty unclear to me how the different templates work together and what you are trying to achieve, but I assume the problem is in this line:

```
164 |      >>= loadAndApplyTemplates ["tags", "blog", "default"]
```

You are applying your `blog` template here, which refers to things like `$tags$` and `$date$`.  This is not really applicable, since you've already rendered the posts as a string.  I think you want this instead:

```
164 |      >>= loadAndApplyTemplates ["tags", "default"]
```

I would also recommend using something like `$for(posts)$` instead of rendering it to a string as you are doing -- that would allow you to reuse more code.

**Comment by Rizary** [comment]
Hi @jaspervdj thank you for your enlightenment..

the different template is only for combining each other.. I have delete the "blog" and it works. I am still learning how that happened though..

could you please let me know the example of using ```$for(posts)$```, i still not quite sure about how to use it. Did you mean rendering it to a string refer to the post? or the template?
