### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by honza** [jaspervdj/hakyll#59]
Hey, I noticed that the Web module contains a reference to Pandoc. Since Pandoc is GPL, shouldn't hakyll itself be GPL?

Would Hakyll work without Pandoc?

Not trying to be mean, just want to honor the license. 

Thanks

**Comment by pharpend** [comment]
I'm still not convinced on this. Hakyll links to Pandoc, which clearly requires Hakyll to be GPL-licensed. That post on the mailing list mentioned system calls with the Linux kernel. The guy conveniently forgot to mention that the kernel's license provides an explicit exception for system calls: <https://github.com/torvalds/linux/blob/master/COPYING>.

But, in more practical terms, nobody who actually holds a copyright on Pandoc is complaining, so I would let this be.

Also, this issue is 3 years old, and I should let it be.

**Comment by tarleb** [comment]
The important point here is that Hakyll is a library; we use it to build programs. It's those programs which include Pandoc (they don't just link to it), and which would have to be GPL licensed.  If you are  concerned about this, you could add a little note somewhere in the Readme to clear things up for future readers.

**Comment by jsl** [comment]
My understanding is that since [Hakyll links against Pandoc](https://github.com/jaspervdj/hakyll/blob/master/hakyll.cabal#L162), and since Pandoc is GPL, and has no explicit linking exceptions, Hakyll also must be released under the GPL.

It seems to me that this is an important issue, not just for the Hakyll project, but anything that depends on Hakyll. Suppose there is a commercial, closed-source project that depends on Hakyll. Someone wants that source code to be released, so they force Hakyll to change, and then force the upstream company to release their code. That could have huge implications for a commercial projects that integrate Hakyll.

I'd really like to understand if my reasoning is incorrect here - looking forward to hearing your thoughts. Thanks!

**Comment by tarleb** [comment]
As stated above, I believe there is no obligation to license Hakyll as GPL.  If you were to use the Hakyll library to compile a binary, and this library contains pandoc, then yes, that complete program must be GPL licensed.  This still has no consequences unless you distribute the binary.  So if you were to offer a web service using hakyll and pandoc, there would still be no need to release any additional code (that's why the AGPL exists).  Only if you were to offer the binary for download, then the GPL requires you to release the code.

**Comment by jsl** [comment]
Thanks for your response, @tarleb. I agree that if Pandoc used AGPL instead of GPL, it would be more clear that certain users are in violation. However it still looks to me like there are risks for some use cases.

First, it isn't clear to me that Hakyll can be licensed under a license that is incompatible with GPL. It seems that it comes down, perhaps to whether Hakyll is considered a "derived work" which hasn't been precisely defined in legal terms. I found [this article](http://wpandlegalstuff.com/understanding-gpl-licensing-wordpress/) to be useful in understanding the possible issues. Based on my reading of that article, it seems that there is some risk that Hakyll could be forced to be licensed under a variant of the GPL.

If that happens, it seems that programs using Hakyll could have legal issues, depending on how they are used and distributed. While it does seem like personal use, or use in a web service is probably ok , embedding Hakyll in a commercial program that is distributed to users would then seem to be not compliant, unless that commercial program is under the GPL. Also, what if a consultancy builds a program for a client, and then transfers ownership to the client? Does that constitute distribution? I would imagine that if the client wanted to sell the product to other clients, that could only be done if the product is under GPL and the source code is published.

I'm not a lawyer, but it still seems to me like there are considerable risks with the current licensing scenario. At this point, while I wouldn't hesitate to use Pandoc or Hakyll for my personal projects, I also don't think it would be responsible to let our team of developers embed Hakyll or Pandoc in a system that is developed for a client or employer without first apprising them of the possible risks, and advising them to speak with a lawyer to better understand the possible impact on their business.

**Comment by tarleb** [comment]
Interesting link.  IANAL either, and I am out of my depth at this level of detail.  I suggest you ask at the [Open Source SE community](https://opensource.stackexchange.com), you'll get a better and more qualified answer there.

Other options include:

  - ask all contributors for permission (send mails to `git log --format='%aN <%ae>' | sort -u`);
  - try to get the program dual-licensed (unlikely in this case);
  - assume that none of the devs would be interested to sue you over a grey-area issue.
