### ISSUE TITLE
How to manage cross-refereces with Hakyll?

### ISSUE THREAD

**Issue by chshersh** [jaspervdj/hakyll#590]
I'm creating static website using Hakyll. I have posts in format `posts/2017-11-17-my-title.md`. At the end of each post I want to put references to other posts. So I'm trying to use this code example from tutorial

```haskell
postMatcher :: Rules ()
    -- routing, etc.
    posts <- recentFirst =<< loadAll postPath
    let newsCtx = listField "posts" postCtx (return posts)
    -- loadAndApply, etc.

postCtx :: Context String
postCtx =
    dateField "date" "%B %e, %Y" `mappend`
    defaultContext
```

Unfortunately, when I'm trying to do this I see this error:

```
  [ERROR] Hakyll.Core.Runtime.chase: Dependency cycle detected: posts/A.md depends on posts/A.md
```

This is manageable, I resolved this issue using `complement` pattern-combinator. But when I have two posts I see error like this:

```
  [ERROR] Hakyll.Core.Runtime.chase: Dependency cycle detected: posts/A.md depends on posts/B.md depends on posts/A.md
```

So my questions: what is the recommended way to implement cross-references using Hakyll? I guess I can't use `loadAll` in that case. Then what should I use?

**Comment by isovector** [comment]
I'm trying to accomplish the same thing, and having no luck either.

[This post](https://groups.google.com/forum/#!msg/hakyll/W58a6cmE028/7FU4wCzPDgAJ) suggests that using versions of the files is the correct way to make this happen, but it seems to fail with

```
(snapshot content) was not found in the cache, the cache might be corrupted or the item you are referring to might not exist
```

**Comment by GAumala** [comment]
Using versions of files is definitely the way to go. You can have a version of your posts that just contains an id or a link to it and then load that version of the posts you want to reference when you compile the actual posts.

I use Hakyll to take notes of school lessons. For every lesson I create a file inside "lessons" which Hakyll then transforms into an HTML page. Since I'm going to be reviewing these for exams and such, I needed to reference the previous and next lessons at the footer of each page. This was very easy to accomplish using different versions.

In my site, every lesson has a unique base name containing its date. First I create "id" versions of my lessons, which just have the file's basename in the body:

``` Haskell
    match "lessons/*" $ version "id" $ do
        compile $ (makeItem . takeBaseName) 
            =<< getResourceFilePath
```
Then when I generate the actual lesson HTML I load all the lesson id's and find the current lesson's neighbors (the previous and the next, if they exist) using a function named`findLessonPosition`.

``` Haskell
    match "lessons/*" $ do
        route $ setExtension "html"
        compile $ do
            currentLessonId <- takeBaseName `fmap` getResourceFilePath
            lessonIds <- (map itemBody) `fmap` 
                         loadAll ("lessons/*" .&&. hasVersion "id")
            let lessonPos = findLessonPosition currentLessonId lessonIds
            let ctx = 
                    lessonPosCtx lessonPos `mappend`
                    defaultContext

            makeItem ""
                >>= loadAndApplyTemplate "templates/lesson.html" ctx
                >>= relativizeUrls

    lessonPosCtx :: LessonPositon -> Context String
    lessonPosCtx (MidLesson prev next) = 
        constField "prev" prev `mappend`
        constField "next" next
    lessonPosCtx (FirstLesson next) = constField "next" next
    lessonPosCtx (LastLesson prev) = constField "prev" prev
    lessonPosCtx NoLesson = missingField
```

**Comment by EpicOrange** [comment]
GAumala's solution above has been working perfectly for me. I think this issue can be closed.

**Comment by jaspervdj** [comment]
Thanks for the heads up!
