### ISSUE TITLE
Add Contributing Guideline

### ISSUE THREAD

**Issue by wisn** [jaspervdj/hakyll#630]
I think it would be good if Hakyll has contributing guideline so the contributor could follow the writing style, naming convention, etc.

**Comment by onurcanbektas** [comment]
And this would be also helpfull to the developers who are new to this project

**Comment by ksbrar** [comment]
Bump. Would also be nice to know what "big"/significant areas are ripe for development - right now it's just a bunch of individual issues that crop up rather than having a sense of what else is needed. (Alternatively, maybe the codebase is mature enough now that @jaspervdj feels such a list may be unnecessary?)
