### ISSUE TITLE
Add support for MMark as an alternative markdown processor

### ISSUE THREAD

**Issue by mrkkrp** [jaspervdj/hakyll#636]
It's been a while since I used Hakyll myself, so I don't remember how hard this may be. But the fact is, recently I got [a message on Twitter](https://twitter.com/urbanslug/status/997180700154613760):

> Any plans for somehow getting ghc-syntax-highlighter to work in Hakyll despite it currently only  supporting Pandoc?
> A better question might be about MMark support on hakyll.

MMark can only convert from `Text` to HTML (it uses `lucid` but that can be rendered to anything). I don't know if Hakyll uses Pandoc's abilities to convert to different formats (in addition to HTML), if no, then the addition should be simpler.

I think it would be definitely good to make MMark easier to start with by including it into some sort of a framework :)

**Comment by jaspervdj** [comment]
At its core, Hakyll is just a simple build system with a strong bias for websites.  You are really just specifying `Item a -> Compiler (Item b)` rules on how to process your pages.  While Hakyll provides a bunch of convenience functions that make calling Pandoc easier, it's not a requirement: you can compile Hakyll with `--flags="-usepandoc"` to remove the dependency entirely and get a more lightweight Hakyll.

You can define a MMark processor in a few lines:

```haskell
mmarkCompiler :: Item String -> Compiler (Item String)
mmarkCompiler item =
    let txt = T.pack (itemBody item) in
    case MMark.parse (toFilePath $ itemIdentifier item) txt of
        Left errs -> fail $ MMark.parseErrorsPretty txt errs
        Right r   -> return item
            { itemBody = TL.unpack $ L.renderText $ MMark.render r
            }
```

Note that I've chosen to do the conversion to and from `String` here.  This makes it integrate a bit more with the `relativizeUrls` and Hakyll templating (see below).  But again, there's few restrictions here: you can also have `mmarkCompiler :: Item BL.ByteString -> Compiler (Item TL.Text)` if you care a lot about performance.

Using this instead of the usual `pandocCompiler` is straightforward:

```haskell
main = hakyll $ do
    match "news.md"
        route $ setExtension "html"
        compile $
            getResourceBody >>=
            mmarkCompiler >>=
            loadAndApplyTemplate "templates/default.html" defaultContext >>=
            relativizeUrls
```

**Comment by mrkkrp** [comment]
That's great! I'll let that person know about your reply.

**Comment by urbanslug** [comment]
Thanks :smile: that has answers my question perfectly.
