### ISSUE TITLE
Dependency error when running `stack install hakyll`

### ISSUE THREAD

**Issue by ethagnawl** [jaspervdj/hakyll#684]
I'm seeing the following lrucache dependency error when trying to install Hakyll:

```
stack install hakyll
Writing implicit global project config file to: /home/peter/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-13.6
Downloaded lts-13.6 build plan.    
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.6.3.                                      
Installed GHC.                                                                 

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hakyll-4.12.5.1:
    lrucache must match >=1.1.1 && <1.3, but the stack configuration has no specified version (latest matching version is 1.2.0.1) needed since hakyll is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many
    complicated constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps in /home/hello/.stack/global-project/stack.yaml:

lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e

Plan construction failed.
```

I was able to work around this by specifying the lrucache dependency in /home/hello/.stack/global-project/stack.yaml, as the error message suggested, but that shouldn't be necessary.

I also feel like I'm not really grokking the dependency error, since Hakyll has a stack.yml configuration file containing an entry for lrucache which falls within the range defined in hakyll.cabal. Is it possible this file is being ignored by `stack install ...`?

### Environment
Stack: Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1 (newly installed)
OS: Debian 9.7

**Comment by jaspervdj** [comment]
Hi @ethagnawl, `stack.yaml` files are typically "local" to the repository and not distributed.

If you use `stack`, the way I recommend dealing with this is having a `stack.yaml` in your website's repository as well, where you can add `lrucache` to `extra-deps`. For example, you can see I do this on the [ZFoH website here](https://github.com/zfoh/zfoh.ch/blob/master/stack.yaml#L13).

It seems that `lrucache` has had some installation issues for a bit, so it might be a worthwhile project to replace it by the alternative `lrucaching` package.

Feel free to re-open this issue if this does not solve your problem!

**Comment by ethagnawl** [comment]
Thanks for the prompt reply, @jaspervdj!

I'm not sure I was clear enough in my opening comment, so I will back up a bit and reiterate: I'm seeing the behavior documented above when following [the installation tutorial](https://jaspervdj.be/hakyll/tutorials/01-installation.html) using a new Digital Ocean Droplet, with a pristine Debian 9.7 installation and newly installed Stack. (I do have a site built using Hakyll and I was having different dependency issues when attempting to rebuild it after a few months, but that problem is tangential, it's just what led me to trying to follow the tutorial as a sort of smoke test.) 

So, in terms of what I was trying to achieve when running into this issue and your proposed solution: there isn't yet a website/repo with its own stack.yml in which to specify the lrucache extra-deps when this issue surfaces -- I'm still only trying to install hakyll for the first time. I am a complete beginner when it comes to the Haskell packaging ecosystem, but this seems like a bug to me.

**Comment by AlainODea** [comment]
@ethagnawl I got bitten by this as well. I found a solution and an explanation of why it is needed and why it works.

# Quick Fix
Set lts-12.26 as the resolver in ~/.stack/global-project/stack.yaml like this:

```yaml
# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/Users/alain_odea/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-12.26            
```

# Long Explanation

When you (and I) tried to stack install hakyll, Stack automatically picked the latest Stackage LTS. For you, it used Stackage LTS 13.6 (for me it used Stackage LTS 13.21).

The hakyll package was not in Stackage LTS 13.6 (or Stackage LTS 13.21).

You can [search for Hakyll in Stack LTS 13.6 on Stackage.org](https://www.stackage.org/lts-13.6/hoogle?q=hakyll) and see that it is not there 😢 

You can [search for Hakyll in Stack LTS 12.26 on Stackage.org](https://www.stackage.org/lts-12.26/hoogle?q=hakyll) and see that it is 😄 

Hakyll is not, as of this writing, in any release later than Stackage LTS 12.26.

Setting the solver on the global project to a version that has hakyll fixes this. It works because stack can now find a version of hakyll and all of its dependencies to resolve this.

Caveat: switching the solver on the global project does have side-effects though:
1. [Features and fixes in hakyll 4.12.5.0+](https://jaspervdj.be/hakyll/releases.html) will be unavailable
2. It will complicate installing a Haskell tool globally that depends on GHC 8.6+
3. All global Haskell package or tool installs will use GHC 8.4.4 and Stackage LTS 12.26 (I think)

I think the long-term fix for this is to get hakyll back into upcoming Stackage LTS releases somehow. I suspect that may involve switching from **lrucache** to **lrucaching** as @jaspervdj mentions above.

**Comment by ethagnawl** [comment]
Thanks for following up @AlainODea! That's useful information and your PR should be very helpful for others installing Hakyll.

**Comment by AlainODea** [comment]
@ethagnawl my pleasure. I figure it's likely not merge-worthy, but a decent workaround 😄
