### ISSUE TITLE
New changes to site.hs are ignored or cached

### ISSUE THREAD

**Issue by armatures** [jaspervdj/hakyll#744]
After creating a new hakyll site by following [this tutorial](https://jaspervdj.be/hakyll/tutorials/01-installation.html), I decided to simplify the `site.hs` file to make sure I am not missing anything. I deleted most of the file, leaving this:
```
{-# LANGUAGE OverloadedStrings #-}
import           Data.Monoid (mappend)
import           Hakyll

main :: IO ()
main = hakyll $ do
    match "images/*" $ do
        route   idRoute
        compile copyFileCompiler
```
running `stack exec site clean && stack exec site build && ls _site` shows the same contents as before, with a `posts` directory and lots of other files. I ran things a few more times and got the other things removed, but on reverting that change to `site.hs`, I'm having a problem getting them back. It's as though there is some caching or things are running in the background using old versions of this file. This makes any sort of development on my site out of the question, as none of the changes seem to reliably have an effect.

In hopes of getting more clues about this, running `stack exec site build -v` gives a possible clue (eliding most of the output): `... SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-12-09 22:04:51.616752 UTC] ...`. I'm not sure what this is about but I thought I'd mention it.

I restarted my computer and ran `stack exec site build` again, to no avail. With the original `site.hs` file, It won't repopulate the `_site` directory. Does anyone have any idea what might cause such a problem?

**Comment by jaspervdj** [comment]
Hi @armatures,

I think there's some misunderstanding -- Hakyll is a library used to produce an executable typically called `site`.  This executable works a bit like a `Makefile` in that it tracks changed files and dependencies in between them.  However, it does not track change to it's own source or any libraries used to build `site`.  So if you change `site.hs`, you need to build the executable again using `stack build`.

Additionally, `stack exec site build -v` passes the `-v` flag to `stack`; not `site`, so what you're seeing is debug output from `stack`.  In order to pass `-v` to `site`, you need to use something like `stack exec -- site build -v`.

Please do reopen this if anything remains unclear!

**Comment by armatures** [comment]
😬 I felt I must be missing something major, and that this was likely a dumb question. It's a huge relief to get your answer! Thank you for explaining this to me. 😅
