### ISSUE TITLE
The ** pattern doesn't match files starting with dot symbol

### ISSUE THREAD

**Issue by arrowd** [jaspervdj/hakyll#841]
I have `data/.foo` file as well as `data/.hg` directory in my Hakyll project. The following rule

```
match "data/**" $ do
  route idRoute
  compile copyFileCompiler
```

correctly copies all files and directories recursively, except `.foo` and `.hg`.

**Comment by Minoru** [comment]
I think that's the correct behaviour. Since the pattern is specified as a string literal, `IsString` instance applies and [calls `fromGlob`](https://hackage.haskell.org/package/hakyll-4.14.0.0/docs/src/Hakyll.Core.Identifier.Pattern.html#line-82). There is no indication in the docs, but I believe globs are a Unix concept, and those are [documented](https://man7.org/linux/man-pages/man7/glob.7.html) to only match filenames that do *not* start with a dot.

In order to match both, I think you'll have to use something like `"data/**" .||. "data/**/.*"` (I didn't test this though).

**Comment by arrowd** [comment]
Unfortenately, `data/**/.*` didn't work too.

**Comment by Minoru** [comment]
How about [`fromRegex`](https://hackage.haskell.org/package/hakyll-4.14.0.0/docs/Hakyll-Core-Identifier-Pattern.html#v:fromRegex)? Something like `match (fromRegex "^data/.*")` should match *everything* under the "data" directory, I think.

**Comment by arrowd** [comment]
Nope, the regex works the same as glob with two stars. I guess, the problem lies deeper, in the filesystem visiting code.

**Comment by Minoru** [comment]
That'd be `Hakyll.Core.Provider`. I don't see anything suspicious in the code: it uses `System.Directory.getDirectoryContents` which returns *everything*, and it filters out just `.` and `..`. I won't dig deeper right now, so if you take a look and discover something, please share!

**Comment by Minoru** [comment]
@arrowd Did you manage to figure out what's wrong with the `Provider`?

**Comment by arrowd** [comment]
Not yet, but it is on my TODO.

**Comment by arrowd** [comment]
The problem stems from the default `Configuration`, the `ignoreFile` field:

```
    ignoreFile' path
        | "."    `isPrefixOf` fileName = True
        | "#"    `isPrefixOf` fileName = True
        | "~"    `isSuffixOf` fileName = True
        | ".swp" `isSuffixOf` fileName = True
        | otherwise                    = False
```

Overriding it for my site fixes the problem. I don't think that default should be changed, as it might suddenly make VCS directories visible for users.

**Comment by Minoru** [comment]
Oh! So simple… Thank you for writing back! :+1:
