### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by malteneuss** [jaspervdj/hakyll#904]
Every time i work on my Hakyll-generated blog after some time i need to rewrap my head around the relation between the content files and `Pattern`, `Identifier`, `Item` and `Compiler` etc., and i always end up having to look at the Hakyll source code. So, it would be nice to extend the documentation with more info (to make using Hoogle sufficient) and possibly more small usage examples.

I'll be willing to help with that if there's a need from others as well and the willingness to merge changes in small increments.

ps: I'm asking before investing time, because there are pending PRs being unresolved for years. I'm heavily invested in Hakyll (see [lambdablob.com](https://lambdablob.com)) and would like it to thrive even more.

**Comment by Minoru** [comment]
I'll gladly merge those PRs!

I haven't worked up the courage to go through the backlog of PRs though; their authors have probably moved on by now, so I can't request any changes — it's either merge as-is, close, or take it upon myself to bring it to mergeable state. I don't know when I'll have energy for that, but I at least keep abreast of all the new PRs.

Do you want to keep this issue open so you can reference it, or should it be closed? It can't really be resolved, because there's no clear way to tell when the documentation was improved :)

**Comment by malteneuss** [comment]
Perfect. I'll start working on it on the weekend. 

I would like to keep this ticket open for referencing and for discussions if some other people feel the need to mention parts they find confusing. 

Regarding the open PRs/tickets, from project management people at my company i learned that it's beneficial to limit WIP items to a minimum. PRs and issues that haven't been touched for years (and that aren't absolutely essential) will most likely never be finished. It also may leave a bad impression on people that have to decide between Hakyll and another generator (i'm thinking of Non-Haskellers like me in the past when i had to decide between XMonad and another window manager. XMonad felt active enough to give it a try). Maybe we could use an autoclose bot to close issues after a year or so of inactivity? Would it help to add a policy that people who want to contribute code should open an issue first to get feedback? Especially if there is enough time from the maintainers, before investing time in preparing the PR?

**Comment by Minoru** [comment]
I agree that PRs should be closed after a while. I just haven't had the heart to do it :)

I disagree that old issues should be closed. The "stale bot" that's so popular on GitHub is quite annoying, making me check in once a few months to say that yes, the issue is still relevant. In my own projects, I keep old issues open either because I still think they should be fixed, or because I like the ideas but can't implement them just yet.

I don't think Hakyll sees enough activity to warrant any new policies. Contributors are free to pick whatever route they're comfortable with, and from the reviewer's perspective, I'm fine with that.

I should note that I'm not the author of Hakyll, I'm just trying to keep the place tidy :) So the above is my opinion, and what I'm leaning towards.

**Comment by malteneuss** [comment]
> I keep old issues open either because I still think they should be fixed, or because I like the ideas but can't implement them just yet.
That's a valid point. I think that's what the `exemptLabels` list is for in [stalebot](https://github.com/apps/stale). Would this be a solution for `doc`, `feature` and `bug` labels (or a new `important` label)? (I was thinking more about the many issues like #794 that are abandoned by the creators).

> I don't think Hakyll sees enough activity to warrant any new policies. Contributors are free to pick whatever route they're comfortable with, and from the reviewer's perspective, I'm fine with that.
Ok, maybe i should have used the term suggestion or encourage to avoid frustration with bigger changes^^ . I certainly would be frustrated if i had invested a lot of time in making my changes PR-ready only to find out that there's no interest or time to merge them. However, i see that it would be overkill for the many small PRs like version bumps or fixing typos that frequently get merged.

**Comment by Minoru** [comment]
Yup, `examptLabels` would work, but I still think that only a human can decide if it's time to close an issue. So I'm still opposed to the idea of a bot doing it.

I don't know if/when I find energy to go through the existing issues and close the ones that look hopeless, but I closed #794 now. One down, 97 to go :) Thanks for pointing it out!
