### ISSUE TITLE
Use of `unsafePerformIO`

### ISSUE THREAD

**Issue by throwaway1037** [jaspervdj/hakyll#951]
https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Main.hs#L202
`progName = unsafePerformIO getProgName`

Is the use of `unsafePerformIO` necessary?
Is there a reason this cannot be done safely, or was this a post-hoc addition?

I think refactoring it to be a safe call to `getProgName` would require modifying the functions which use `progName`.

**Comment by Minoru** [comment]
Hi! Judging by `git log --patch --follow lib/Hakyll/Main.hs`, this used to be an implementation detail that became a part of the interface with #755. Now, we can't easily avoid `unsafePerformIO` because the users of the value don't use the `IO` monad.

I don't see much harm in this call though. It simply looks at the first element of `argv`, which is technically not a constant, but practically is.

I'll merge a PR that refactors this, preferably in a way that doesn't change the existing type signatures (so add a new function, deprecate the old one). But I honestly don't think that this is worth an effort, so I'll close this issue now.
